#
name: fastapi를 aws linux에 배포하기

on:
  push:
    branches: ["master"] # master 브렌치에 push될 때 아래의 job 실행

jobs:
  deploy:
    runs-on: ubuntu-lates
    steps:
      - name: ssh 원격 명령
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd ~/hello_fastapi
            git pull origin master
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            fuser -k 8000/tcp || true
            nohup python3 -m uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &